import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getFirestore,collection,doc,onSnapshot,writeBatch,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig} from './js/firebase-config.js';
const db=getFirestore(initializeApp(firebaseConfig));
const event='evans-2026-10-02';
const slots=document.querySelector('#slots'), loading=document.querySelector('#loading'), choice=document.querySelector('#choice'), message=document.querySelector('#message'), submit=document.querySelector('#submit'), form=document.querySelector('#booking');
let selected=null, occupied=new Set(), ready=false;
function time(index){const mins=7*60+index*15;return new Date(2026,9,2,Math.floor(mins/60),mins%60).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}
function render(){slots.replaceChildren();for(let i=0;i<25;i++){const id=String(i).padStart(2,'0'), button=document.createElement('button');button.type='button';button.className='slot'+(selected===id?' selected':'');button.textContent=time(i)+(occupied.has(id)?' · Taken':'');button.disabled=!ready||occupied.has(id);button.setAttribute('aria-pressed',String(selected===id));button.addEventListener('click',()=>{selected=id;choice.textContent='Selected: '+time(i)+'–'+time(i+1);submit.disabled=false;message.textContent='';render()});slots.append(button)}}
render();
onSnapshot(collection(db,'conferenceAvailability',event,'slots'),snapshot=>{occupied=new Set(snapshot.docs.map(d=>d.id));ready=true;loading.textContent='';if(occupied.has(selected)){selected=null;choice.textContent='That time was just reserved. Please choose another.';submit.disabled=true}render()},()=>{loading.textContent='Unable to load times. Please refresh or contact Mr. Evans.';ready=false;render()});
form.addEventListener('submit',async e=>{e.preventDefault();if(!selected||occupied.has(selected)||!ready)return;const id=selected;submit.disabled=true;message.textContent='Reserving your time…';message.className='';const slot=doc(db,'conferenceAvailability',event,'slots',id), booking=doc(db,'conferenceBookings',event,'slots',id);const batch=writeBatch(db);batch.set(slot,{reserved:true,createdAt:serverTimestamp()});batch.set(booking,{studentName:document.querySelector('#student').value.trim(),guardianName:document.querySelector('#parent').value.trim(),email:document.querySelector('#email').value.trim(),phone:document.querySelector('#phone').value.trim(),createdAt:serverTimestamp()});try{await batch.commit();const i=Number(id);message.textContent='Confirmed for Friday, October 2, '+time(i)+'–'+time(i+1)+'. Please save this confirmation.';message.className='success';selected=null;choice.textContent='Reservation confirmed.';form.querySelectorAll('input').forEach(input=>input.disabled=true);render()}catch(err){message.textContent='This slot could not be reserved. It may have just been taken. Please choose another time or refresh.';message.className='error';submit.disabled=false;console.error(err)}});
