import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,doc,onSnapshot,writeBatch} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig,ADMIN_EMAIL} from './js/firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),event='evans-2026-10-02';
const $=id=>document.getElementById(id);let unsubscribe=()=>{},bookings=new Map();
function time(i){let m=7*60+i*15;return new Date(2026,9,2,Math.floor(m/60),m%60).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}
function render(){let rows=$('rows');rows.replaceChildren();$('count').textContent=`Conference times · ${bookings.size} reserved / 25`;for(let i=0;i<25;i++){let id=String(i).padStart(2,'0'),b=bookings.get(id),row=document.createElement('div');row.className='row';let timeCell=document.createElement('strong');timeCell.textContent=time(i);let info=document.createElement('div');if(b){let name=document.createElement('strong');name.textContent=b.studentName||'Student';info.append(name,document.createElement('br'),document.createTextNode(`${b.guardianName||''} · ${b.email||''}${b.phone?' · '+b.phone:''}`));let cancel=document.createElement('button');cancel.className='danger';cancel.textContent='Cancel booking';cancel.addEventListener('click',()=>remove(id,b,cancel));row.append(timeCell,info,cancel)}else{info.textContent='Available';info.className='muted';row.append(timeCell,info)}rows.append(row)}}
async function remove(id,b,button){if(!confirm(`Cancel ${time(Number(id))} for ${b.studentName}? This will reopen the time for parents.`))return;button.disabled=true;$('status').textContent='Cancelling booking…';try{let batch=writeBatch(db);batch.delete(doc(db,'conferenceBookings',event,'slots',id));batch.delete(doc(db,'conferenceAvailability',event,'slots',id));await batch.commit();$('status').textContent=`${time(Number(id))} is open again.`}catch(e){button.disabled=false;$('status').textContent='Could not cancel. Please try again.';console.error(e)}}
$('login').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){$('status').textContent='Sign-in did not finish. Try again.';console.error(e)}};$('logout').onclick=()=>signOut(auth);
$('csv').onclick=()=>{let lines=[['Time','Student','Parent or guardian','Email','Phone']];for(let i=0;i<25;i++){let b=bookings.get(String(i).padStart(2,'0'))||{};lines.push([time(i),b.studentName||'',b.guardianName||'',b.email||'',b.phone||''])}let csv=lines.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='conferences-2026-10-02.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
onAuthStateChanged(auth,user=>{unsubscribe();bookings.clear();$('schedule').hidden=true;$('csv').hidden=true;$('login').hidden=!!user;$('logout').hidden=!user;$('who').textContent=user?`Signed in as ${user.email}`:'Only Mr. Evans can view family details.';if(!user)return;if(user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){$('status').textContent='This account does not have access to conference details.';return}$('status').textContent='Loading schedule…';unsubscribe=onSnapshot(collection(db,'conferenceBookings',event,'slots'),snap=>{bookings=new Map(snap.docs.map(d=>[d.id,d.data()]));$('schedule').hidden=false;$('csv').hidden=false;$('status').textContent='';render()},e=>{$('status').textContent='Could not load bookings. Check your account permissions.';console.error(e)})});
